spring:
  application:
    name: product-service
  config:
    import:
      - optional:nacos:minimart-common.yaml?group=MINIMART
      - optional:nacos:${spring.application.name}.yaml?group=MINIMART
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      discovery:
        namespace: ${NACOS_NS:dev}
        group: MINIMART
      config:
        namespace: ${NACOS_NS:dev}
        group: MINIMART
        file-extension: yaml

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
