spring:
  application:
    name: product-service
  jackson:
    default-property-inclusion: non_null
  cloud:
    compatibility-verifier:
      enabled: true
  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:${DB_PORT:3306}/minimart_product?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DB_USERNAME:minimart}
    password: ${DB_PASSWORD:minimart}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-}]"
